# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        user_db_provider:
            entity:
                class: MedioAmbienteBundle:Usuarios
                property: username

    encoders:
        Symfony\component\Security\Core\User\User: plaintext
        MedioAmbienteBundle\Entity\Usuarios: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        medio_ambiente:
            anonymous: ~
            pattern: ^/
            provider: user_db_provider

            form_login:
                login_path: /login
                check_path: /login
                default_target_path: panel

            logout:
                path: /logout
                target: /

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - {path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/distritos$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/panel/contaminacion/distrito-indicador$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/panel/contaminacion/distrito$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/panel/contaminacion/distrito1-distrito2$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/panel/contaminacion, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/panel, roles: [ROLE_ADMIN,ROLE_USER]}
        - {path: ^/panel/usuarios, roles: [ROLE_ADMIN]}
