<?php

namespace MedioAmbienteBundle\Repository;

/**
 * ContaminacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContaminacionRepository extends \Doctrine\ORM\EntityRepository
{
}
